### ISSUE TITLE
extension not found

### ISSUE THREAD

**Issue by devarni** [jaydenlin/ctags-support#1] opened 2016-09-06 10:23 UTC
extension.findCTags' not found.
Bug with installation?

**Comment by munepom** [comment] 2016-10-12 16:10
me too...
I'm using VSCode 1.6.0

**Comment by rjcoelho** [comment] 2016-11-02 12:54
Same issue

**Comment by japboy** [comment] 2016-11-11 02:46
same here

**Comment by kb-ptti** [comment] 2016-11-18 08:39
Sadly, same for me...

command 'extension.findCTags' not found

when I press Command-T on my Mac.

This is with Visual Studio Code Version 1.7.1 (1.7.1)

**Comment by ivopt** [comment] 2016-11-30 18:02
same here, command 'extension.findCTags' not found .. :(

**Comment by rjcoelho** [comment] 2016-12-01 13:33
Its provabably because it requires a native extension and vscode doesnt Support it

**Comment by vintagenib** [comment] 2016-12-05 16:25
It's the same issue here with me (macOS Sierra + vscode 1.7.2).

The developer console shows a "Module version mismatch" when trying to activate the extension (attached image).
<img width="552" alt="screen shot 2016-12-05 at 10 23 23 am" src="https://cloud.githubusercontent.com/assets/12938168/20892769/14a2e9fa-bad5-11e6-9a34-6119f401f15c.png">

**Comment by freegodly** [comment] 2016-12-08 13:42
me too

**Comment by fadeevab** [comment] 2016-12-20 09:05
Same issue

**Comment by jaydenlin** [comment] 2017-01-09 03:09
Sorry for reply late... I am working on it.

**Comment by robert-r-meyer** [comment] 2017-01-19 16:47
Same issue here. Thanks for working on it.

**Comment by yeah2569** [comment] 2017-02-03 05:38
me too

**Comment by gliush** [comment] 2017-02-07 11:23
me too

**Comment by devkaiwang** [comment] 2017-02-21 08:05
same here

**Comment by niaiwomattt** [comment] 2017-03-04 05:15
me too 
Reported on vscode 1.10.1: command 'extension.findCTags' not found. Did not find other parts of the error, I think it should be your program and the new version is not compatible? I hope you can update as soon as possible. Thank you.

**Comment by jtanx** [comment] 2017-03-08 09:38
Yeah the issue is that the `ctags` native module needs to be recompiled against electron 1.4.6. But I'm also seeing some issue with it not actually locating the definition within the file properly - something to do with grep.js/fileGrep not working...

----

I figured out that issue - it was treating the ctags pattern as a regex when it's not *really* one - it just has the ^$ parts to denote the start/end matching, as far as I can tell.

I've rolled a VSIX that will work on Windows VS Code 1.10.1: https://github.com/jtanx/ctags-support/releases/tag/1.0.8 (no Linux support because of that dependency on the ctags native module and I haven't compiled for those targets)

**Comment by canucks2005** [comment] 2017-03-10 23:02
I tried this extension on Windows VS Code 1.10.2. It does not work. Give the same error 'extension.findCTags' not found.

**Comment by jtanx** [comment] 2017-03-10 23:52
¯\_(ツ)_/¯ it works for me. 

* Are you sure you're installing the vsix correctly? e.g. `code --install-extension ctags-support-1.0.8.vsix`?
* Does it show up as version 1.0.8 in the list of installed extensions?
* If you go 'Help->Developer tools->Console' then try to use the extension, see what errors it says

**Comment by boer0924** [comment] 2017-03-12 10:39
vscode 1.10.2 & ctags-support1.0.7 

'extension.findCTags' not found. 

@jtanx where find 1.0.8 version?

**Comment by canucks2005** [comment] 2017-03-12 15:44
@jtanx You are right. Actually I did not install the 1.0.8 version correctly. I'm new to the vscode. I run the code --install-extension ctags-support-1.0.8.vsix command in the windows cmd, but nothing happened.

Where should I run the above command?

**Comment by canucks2005** [comment] 2017-03-12 15:46
@boer0924 you can find 1.0.8 version extension at jtanx 4 days ago post:

I've rolled a VSIX that will work on Windows VS Code 1.10.1: https://github.com/jtanx/ctags-support/releases/tag/1.0.8 (no Linux support because of that dependency on the ctags native module and I haven't compiled for those targets)

**Comment by jtanx** [comment] 2017-03-12 21:19
For the method I mentioned, you need to use a command prompt:

![vscode](https://cloud.githubusercontent.com/assets/5137410/23836039/96be6792-07c5-11e7-8bdc-89757ad92bf5.png)

But from this post: http://stackoverflow.com/a/38866913 (see the last screenshot)

You can do it from inside VSCode - Click on the three dots in the Extensions window and select "Install from VSIX..." select the VSIX to be installed, then restart VSCode

**Comment by canucks2005** [comment] 2017-03-12 21:54
@jtanx Thanks for reply. From command prompt, I entered the same command as you described above, but it just hang there forever. However I tried to install from GUI extension pull down menu "Install from VSIX", installed successfully.

**Comment by jcloutz** [comment] 2017-03-30 20:19
@jtanx I see that yours is compiled to target windows. What would need to be done to compile it for mac?

**Comment by jtanx** [comment] 2017-03-31 09:28
@jcloutz  this package has a dependency on the [ctags](https://www.npmjs.com/package/ctags) package, which requires compilation on the target platform eg macos. Not only that, but it must be compiled with support for electron 1.4.6 (see here https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)

**Comment by gayuna** [comment] 2017-04-05 05:44
same problem with VSCode 1.10.2 on windows 7 and CTags support 1.0.7.
And I wasn't able to download v1.0.8 from @jtanx 's repository because of security policy of my company. 
gosh. :(

**Comment by caneroj1** [comment] 2017-04-17 12:55
Has there been any progress on this issue? I'm having the same `extension.findCTags not found` problem.

I'm on VSCode 1.11.2 and macOS Sierra 10.12.4.

**Comment by gikey** [comment] 2017-04-20 03:38
Me too. How to resolve this issue ?

**Comment by Skarlso** [comment] 2017-04-20 07:57
So this extension is still not working. What's up?
`command 'extension.findCTags' not found`

**Comment by rabidt** [comment] 2017-04-20 20:55
@jtanx your release 1.0.9 changes seem to work but actual code is not checked in I think?

**Comment by jtanx** [comment] 2017-04-20 21:13
@Odoth my changes are checked in, only on my own fork, since I don't own this repo: https://github.com/jtanx/ctags-support/commits/master

Although my assumption about it not being a regex is wrong - it is one, it's just a vim regex. But it still works in most cases...

**Comment by jtanx** [comment] 2017-04-21 08:39
@Odoth oops... on second inspection you're right - I had staged the changes for commit but never committed it. https://github.com/jtanx/ctags-support/commit/02adad594b80778df8b6986f451fe0c48ed06532

**Comment by jaydenlin** [comment] 2017-04-23 16:36
@jtanx 
Thank you for the feedback.
Could you send a PR to the repo ?
I can merge it and publish the new version

**Comment by jtanx** [comment] 2017-04-23 20:32
@jaydenlin sure, I could submit my modifications, but they won't help with the [ctags](https://github.com/atom/node-ctags) package which is the cause of the 'extension not found' issue - especially if you want to make this extension work cross-platform.

**Comment by niaiwomattt** [comment] 2017-04-24 01:56
Has anyone improved this function? Merge as soon as possible, thank you very much!

**Comment by rabidt** [comment] 2017-04-24 04:06
Would be great to replace the native module ctags dependency with pure js implementation but I don't see any equivalent module, and possibly the performance won't be good enough...I'll be playing with writing it, hopefully it will be viable.

**Comment by jtanx** [comment] 2017-04-24 08:08
@Odoth yeah I'm actually working (was working?) on a native js implementation,.

The worst thing is that it's difficult to have random file access while also knowing your position in the file - which is needed to perform the binary search. I think I've found a solution to this, but I've somewhat lacked the time or motivation to finish it off.

And yeah, performance is definitely worse than a pure C implementation... and all the async io cruft certainly doesn't help. Some rudimentary testing shows it's ~1.7-2x slower than the C implementation (~300ms lookup vs ~170-180ms lookup on a 15MB tags file)

----

FWIW I reckon it wouldn't be too hard to make a frankenstein node-ctags package that bundled all the prebuilt binaries needed for it to work cross-platform. I'm just annoyed that npm doesn't allow making pre-built binary packages by default...

**Comment by rabidt** [comment] 2017-04-24 21:51
@jtanx According to vscode extension docs it's not a great idea, biggest reason being you have to recompile the binaries any time vscode changes version of node (or possibly every new version of vscode??? not 100% clear):
https://code.visualstudio.com/docs/extensionAPI/patterns-and-principles#_common-questions

2x slower is pretty tolerable IMO, though I'm curious what the numbers will look like with very large tag files (multi gigabyte) which is my use case. 

Are you doing full async with all the fs calls? The C version is defacto synchronous anyway so I figure doing it all sync in js is a valid approach. My understanding is that all extensions share a process, so worst case scenario your other extensions can't process while your search runs (which, again, is the current behavior using the C module).

**Comment by jtanx** [comment] 2017-04-24 22:01
@Odoth it's fully asynchronous. I'm not completely familiar with the vscode setup, so I was under the impression that if you had synchronous code, you're locking up the whole editor. But looking at the task manager, I see multiple processes/instance, so I guess this isn't actually the case.

With regards to having to recompile with vscode upgrades, that's definitely true, but I don't think vscode updates its nodejs runtime all that often.

**Comment by rabidt** [comment] 2017-04-24 22:06
@jtanx Ah ok interesting. I just came up with the justification for going synchronous is because I'm not savvy enough to know how to approach the problem with async. Sounds like you are :1st_place_medal: I'm curious to see your code.

**Comment by niaiwomattt** [comment] 2017-04-27 02:13
Look forward to a long time, when issued a version can be used?

**Comment by jaydenlin** [comment] 2017-04-30 18:32
@devarni @niaiwomattt @Odoth @jtanx @Skarlso @gikey @caneroj1  @gayuna @jcloutz @canucks2005 @niaiwomattt @SuperWangKai @gliush @yeah2569 @robert-r-meyer @fadeevab @freegodly @vintagenib @rjcoelho @LynxEyes @kb-ptti @japboy @rjcoelho @munepom @devarni
Feel very very sorry for the long waiting. 
I just publish the new version with native javascript implement.
(https://marketplace.visualstudio.com/items?itemName=jaydenlin.ctags-support)
It could be a little slow. but it works. I will find other way to speed it up.  
thx

**Comment by Skarlso** [comment] 2017-04-30 18:38
Dude awesome work, don't sweat it. :-)

**Comment by jaydenlin** [comment] 2017-04-30 20:33
Not sure what happened. it works in my debug mode. but fails by installing.

**Closed as completed** 2017-05-01 09:07 UTC
